name: Daily

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deepface:
    uses: ./.github/workflows/remote-repo-build-image.yml
    secrets: inherit
    with:
      owner: serengil
      repo: deepface

  # unstructured-api:
  #   uses: ./.github/workflows/remote-repo-build-image.yml
  #   secrets: inherit
  #   with:
  #     owner: unstructured-io
  #     repo: unstructured-api
