name: Build docker image of remote repo

on:
  workflow_call:
    inputs:
      owner:
        description: "Owner of the remote repository"
        required: true
        type: string
      repo:
        description: "Name of the remote repository"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Get latest release of remote repository
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          excludes: prerelease, draft

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup GCP Authentication
        id: auth
        uses: abinnovision/actions@setup-gcp-v1
        with:
          auth: ${{ vars.GCP_AUTH }}
          token_format: access_token

      - name: Setup Docker Auth
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.GCP_AR_DOCKER_URL }}/${{ inputs.owner }}-${{ inputs.repo }}:latest
            ${{ vars.GCP_AR_DOCKER_URL }}/${{ inputs.owner }}-${{ inputs.repo }}:${{ steps.release.outputs.release }}
          context: https://github.com/${{ inputs.owner }}/${{ inputs.repo }}.git#${{ steps.release.outputs.release }}
