name: Scheduled image builds

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deepface:
    uses: ./.github/workflows/remote-repo-build-image.yml
    secrets: inherit
    with:
      owner: serengil
      repo: deepface
